default:
    image:
        name: docker-registry.codasip.com/platforms/qemu:0.1.1
        entrypoint: [""]
    interruptible: true
    tags:
        - docker
        - linux
        - nolicense

build_qemu_riscvcheri_64:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv64cheri 

build_qemu_riscvcheri_32:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri riscv32cheri 

build_qemu_morellocheri:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri morello

build_qemu_mipscheri:
    stage: build
    script:
        - scripts/riscv_cheri/build_riscv_cheri mips64cheri128
